#!/bin/bash

env=$1


export AWS_PROFILE=mzakany
export PERFIN_CLI=1

if [ -z "$env" ]
then
export PERFIN_ENV=prod DEACTIVATE_SENTRY=1
else
export PERFIN_ENV=${env} DEACTIVATE_SENTRY=1
fi


cd ~/Desktop/perfin
source ~/Desktop/perfin/env/bin/activate
python ~/Desktop/perfin/perfin_cli.py $0 $1 $2