service: perfin

provider:
  name: aws
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
  stage: ${opt:stage, 'dev'}
  runtime: python3.7
  environment:
    ES_NODE: ${file(./config/${self:provider.stage}.json):ES_NODE}
    ES_USER: ${file(./config/${self:provider.stage}.json):ES_USER, ''}
    ES_PASS: ${file(./config/${self:provider.stage}.json):ES_PASS, ''}
    INDEX: ${file(./config/${self:provider.stage}.json):INDEX, ''}
    SENTRY_KEY: ${file(./config/${self:provider.stage}.json):SENTRY_KEY, ''}
    CLIENT_ID : ${file(./config/${self:provider.stage}.json):CLIENT_ID, ''}
    SECRET : ${file(./config/${self:provider.stage}.json):SECRET, ''}
    PUBLIC_KEY : ${file(./config/${self:provider.stage}.json):PUBLIC_KEY, ''}
    PLAID_ENV : ${file(./config/${self:provider.stage}.json):PLAID_ENV, ''}

package:
 include:
   - perfin/util/**
   - perfin/lib/**
 exclude:
   .circleci/**
   - docs/**
   - cli/**
   - perfin_cli.py
   - perfin/tests/**
   - perfin/serverless.yml
   - __pycache__/**
   - .pytest_cache
   - .git/**
   - .coverage
   - node_modules/**
   - serverless.yml
   - package-lock.json
   - package.json
   - README.md

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  periodic_ingest:
    handler: perfin.handler.upload_transactions
    timeout: 30
    resevedConcurrency: 1
    events:
      - schedule: rate(1 day)

  ingest_files:
    handler: perfin.handler.process_files
    description: Uploads files from S3 into Elasticsearch
    timeout: 30
    reservedConcurrency: 10
    events:
      - s3:
          bucket: mzakany-perfin
          event: s3:ObjectCreated:*
          existing: true

plugins:
  - serverless-python-requirements
