service: perfin

provider:
  name: aws
  stage: ${opt:stage, 'base'}
  runtime: python3.7
  environment:
    ES_NODE: ${file(./config/${self:provider.stage}.json):ES_NODE}
    ES_USER: ${file(./config/${self:provider.stage}.json):ES_USER, ''}
    ES_PASS: ${file(./config/${self:provider.stage}.json):ES_PASS, ''}
    S3: ${file(./config/${self:provider.stage}.json):S3, ''}
    SENTRY_KEY: ${file(./config/${self:provider.stage}.json):SENTRY_KEY, ''}
package:
 include:
   - perfin/util/**
   - perfin/lib/**
 exclude:
   - docs/**
   - perfin/tests/**
   - perfin/serverless.yml
   - perfin/tests/*
   - .git/*
   - node_modules/*
   - serverless.yml
   - package-lock.json
   - package.json
   - README.md

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  perfin_ingest:
    handler: perfin.handler.process_files

plugins:
  - serverless-python-requirements
