service: perfin

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: python3.7
  environment:
    ES_NODE: ${file(./config/${self:provider.stage}.json):ES_NODE}
    ES_USER: ${file(./config/${self:provider.stage}.json):ES_USER, ''}
    ES_PASS: ${file(./config/${self:provider.stage}.json):ES_PASS, ''}
    SENTRY_KEY: ${file(./config/${self:provider.stage}.json):SENTRY_KEY, ''}
    CLIENT_ID : ${file(./config/${self:provider.stage}.json):CLIENT_ID, ''}
    SECRET : ${file(./config/${self:provider.stage}.json):SECRET, ''}
    PUBLIC_KEY : ${file(./config/${self:provider.stage}.json):PUBLIC_KEY, ''}
    PLAID_ENV : ${file(./config/${self:provider.stage}.json):PLAID_ENV, ''}
package:
 include:
   - perfin/util/**
   - perfin/lib/**
 exclude:
   - docs/**
   - cli/**
   - perfin_cli.py
   - perfin/tests/**
   - perfin/serverless.yml
   - __pycache__/**
   - .pytest_cache
   - .git/**
   - .coverage
   - node_modules/**
   - serverless.yml
   - package-lock.json
   - package.json
   - README.md

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  ingest_files:
    handler: perfin.handler.process_files

plugins:
  - serverless-python-requirements
