# Python CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            curl -sSL https://install.python-poetry.org | python3 -
            poetry
            poetry config virtualenvs.in-project true
            poetry install

      - save_cache:
          paths:
            - .venv
          key: v1-dependencies-{{ .Environment.CIRCLE_SHA1 }}

  test:
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: run tests
          command: |
            make test


workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
           - build
